# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0003_auto_20180224_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tb_app.User')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tb_app.TripSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tb_app.User')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tb_app.TripSchedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='tripuser',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TripUser',
        ),
    ]
