# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_app', '0005_auto_20180225_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tb_app.User'),
        ),
    ]
